- name: playbook variable
  hosts: local
  connections: local
  vars:  
    NAME: "krishna"
    AGE: "23"

  tasks:
  - name: taskbook variable
    ansible.builtin.debug:
      msg: (My Name Is:{{NAME}})
    ansible.builtin.debug:  
      msg: (Age Is:{{AGE}})