- name: hello krishna
  hosts: local
  connection: local
  
  tasks:
  - name: print hello krishna
    ansible.builtin.debug:
      msg: "hello krishna!"


- name: hello
  hosts: web

  tasks: 
  - name: reply:hello
    ansible.buitin.debug:
      msg: "replied: hello"
