- name: playbook variable
  hosts: local
  connection: local
  vars:  
    NAME: "krishna"
    AGE: "23"

  tasks:
  - name: taskbook variable
    vars:
      name: "Ravi"
    ansible.builtin.debug:
      msg: "My Name Is: {{NAME}}, Age Is: {{AGE}}"