- name: arguement priority
  hosts: local
  connection: local
  vars:
    COURSE: python

  tasks: 
  - name: print variables from args
    ansible.builtin.debug:
      msg: "my course is : {{ COURSE }}"