- name: shell
  hosts: local
  connection: local

  tasks:
  - name: shell
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: listing

  - name: print output
    ansible.builtin.debug:
      msg: "{{ listing }}"

  - name: command
    ansible.builtin.command: mkdir file.txt
    register: user_root

  - name: print root 
    ansible.builtin.debug:
      msg: "{{ user_root }}"