- name: shell
  hosts: local
  connection: local

  tasks:
  - name: shell
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: listing

  - name: print output
    ansible.builtin.debug:
      msg: "{{ listing }}"

  - name: command
    ansible.builtin.command: mkdir -p file.txt
    register: user_root

  - name: print root 
    ansible.builtin.debug:
      msg: "{{ user_root }}"

  - name: add info to file
    ansible.builtin.shell: ls -ltr > file.txt
    register: adding

  - name: print added files
    ansible.builtin.debug:
      msg: "{{ adding.stderr }}"       