- name: demo of loops
  hosts: local
  connection: local

  tasks:
  - name: print loops
    ansible.builtin.debug:
      msg: "hii this is {{ item }}"

    loop:
    - krishna
    - ravi
    - harini
    - akshay  