# - name: install package
#   hosts: local
#   connection: local
#   become: yes
  
#   tasks:
#   - name: installed
#     ansible.builtin.package:
#       msg: "{{ item }}"
#       state: present

#     loop:
#     - mysql
#     - nginx   

- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent
    loop:
    - mysql
    - nginx
    - zip
  