- name: demo on filters
  hosts: local
  connection: local
  vars:
   skills: python, ansible, linux, shell

  tasks:
  - name: default printing
    ansible.builtin.debug:
      msg: " hii this is {{ introduce | default('harini')}}"  

  - name: loop
    ansible.builtin.debug:
      msg: "this are my skills: {{ item }}"

    loop: 
    - skills      