- name: demo on filters
  hosts: local
  connection: local
  vars:
   skills: python, ansible, linux, shell

  

  tasks:
  - name: default printing
    ansible.builtin.debug:
      msg: " hii this is {{ introduce | default('harini')}}"  

  - name: string to listing
    ansible.builtin.debug:
      msg: "{{ skills | split(',') }}"