- name: demo on filters
  hosts: local
  connection: local
  vars:
   skills: python, ansible, linux, shell
   tagMap:
    name: project
    tools: ansible
    projectname: roboshop

  tasks:
  - name: default printing
    ansible.builtin.debug:
      msg: " hii this is {{ introduce | default('harini')}}"  

  - name: string to listing
    ansible.builtin.debug:
      msg: "{{ skills | split(',') }}"

  - name: map to listing
    ansible.builtin.debug:
      msg: "{{ tagMap | dict2items }}"    