- name: error handling
  hosts: local
  connection: local

  tasks:
  - name: adding user
    ansible.builtin.command: id roboshop
    register: user_creation
    ignore_errors: true

  - name: user output
    ansible.builtin.debug:
      msg: "{{ user_creation }}"  